# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end

  config.vm.provision "docker" do |d|
    d.build_image "/vagrant" "-t cyberark/pkiaas:latest"
    d.pull_images "captainfluffytoes/dap:11.4.0"
    d.run "conjur-master",
      image: "captainfluffytoes/dap:11.4.0",
      auto_assign_name: true,
      daemonize: true,
      args: "-p 443:443 --security-opt seccomp:unconfined"
  end

end