name: PKIaaS Quality

on:
  pull_request:
    branches: dev

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: jzlai/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}